### PR TITLE
Updated issues template

### PR DESCRIPTION
**Pull request by MarcAnt01**
Hi, a lot of people open issues without checking already opened ones, creating confusion

*By submitting this Contribution you hereby grant to Chris Gamble a worldwide, royalty-free, non-exclusive, perpetual and irrevocable license, with the right to transfer an unlimited number of non-exclusive licenses or to grant sublicenses to third parties, under the Copyright covering the Contribution to use the Contribution by all means, including, but not limited to: publish the Contribution, modify the Contribution, prepare derivative works based upon or containing the Contribution and/or to combine the Contribution with other Materials, reproduce the Contribution in original or modified form, distribute, to make the Contribution available to the public, display and publicly perform the Contribution in original or modified form.*

### CODE REVIEW

**Comment by Fugiman** [comment]
I like the idea, but I'd prefer a different style. I've updated the issue template with a similar message and hopefully it'll help :)

**Comment by MarcAnt01** [comment]
Anyway, you should consider a bot or something that closes issues that don't respect the template, most of reports aren't accurate and just require you to ask for more information, which could be easily avoided

**Comment by Gass-by-Revi** [comment]
@MarcAnt01 @Fugiman Ha mi si me parece una buena idea. De este modo no habría que ir cerrando manualmente aquellos problemas que no respeten la plantilla. A mi por lo menos me parece una buena idea, pero siempre y cuando se pueda realizar.

**Comment by Fugiman** [comment]
While it is frustrating when people don't fill out the template correctly, I personally prefer to respond anyway rather than ignore users with problems. Also many people aren't very technical and are unfamiliar with Github or don't speak English, so some understanding is warranted.

**Comment by Gass-by-Revi** [comment]
Ah, well. thats true

**Pull request closed without merging**
